version: 0.2

phases:
  install:
    commands:
      - cd ${CODEBUILD_SRC_DIR} && npm ci --no-audit
      - cd ${CODEBUILD_SRC_DIR}/cdk && npm ci --no-audit
      - cd ${CODEBUILD_SRC_DIR}/frontend && npm ci --no-audit
  build:
    commands:
      - echo Building Lambdas
      - |
        if [ "$STAGE" == "production" ]; then
          echo Deploying CI infrastructure
          cd ${CODEBUILD_SRC_DIR}/cdk && npm run deploy:ci
        else
          echo Source is not production
        fi

      - echo Building frontend
      - cd ${CODEBUILD_SRC_DIR}/frontend && npm run build:prod
      -
      - echo Deploying APP infrastructure
      - cd ${CODEBUILD_SRC_DIR}/cdk && npm run deploy:app
cache:
  paths:
    - 'cdk/node_modules/**/*'
    - 'frontend/node_modules/**/*'
    - '/root/.npm/**/*'