version: 0.2

phases:
  install:
    commands:
      - cd ${CODEBUILD_SRC_DIR} && npm ci --no-audit
      - cd ${CODEBUILD_SRC_DIR}/cdk && npm ci --no-audit
      - cd ${CODEBUILD_SRC_DIR}/frontend && npm ci --no-audit
  build:
    commands:
      - echo Building frontend
      - cd ${CODEBUILD_SRC_DIR}/frontend && npm run build:prod
      -
      - echo Deploying APP infrastructure
      - cd ${CODEBUILD_SRC_DIR}/cdk && npm run deploy:app
cache:
  paths:
    - '/root/.npm/**/*'