# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --no-audit
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /app/dist

ARG TAG
ENV TAG=${TAG}
RUN echo "<!-- Version: ${TAG}-->" >> /app/dist/index.html

ADD nginx.conf /etc/nginx/

RUN chmod 777 -R /var/cache
RUN chmod 777 -R /var/log/nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
