FROM php:7.2-apache

COPY . /var/www

WORKDIR /var/www

RUN apt-get update && \
    apt-get install -y \
    wget git libzip-dev \
    zip \
      && docker-php-ext-configure zip --with-libzip \
      && docker-php-ext-install pdo pdo_mysql zip

ENV APACHE_DOCUMENT_ROOT /var/www/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN a2enmod rewrite

RUN usermod -u 1000 www-data

# Install Composer
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --silent && \
    mv composer.phar /usr/local/bin/composer

CMD ["/var/www/cmd.sh"]
#RUN usermod -G staff www-data

#ENV PORT 5000
#CMD sed -i "s/80/$PORT/g" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf && docker-php-entrypoint apache2-foreground
