name: RolesTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Assume Role
      uses: youyo/awscredswrap@master
      with:
        role_arn: ${{ secrets.ROLE_ARN }}
        duration_seconds: 3600
        role_session_name: 'awscredswrap@GitHubActions'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
    - name: Identity Check
      uses: actions/aws/cli@master
      with:
        args: sts get-caller-identity
