name: RolesTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Assume Role
        uses: youyo/awscredswrap@master
        with:
          role_arn: ${{ secrets.ROLE_ARN }}
          duration_seconds: 3600
          role_session_name: 'awscredswrap@GitHubActions'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: Identity Check
        run: aws sts get-caller-identity
      - name: Install Docker Compose
        run: |
          echo Installing Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Build Docker Images
        run: |
          npm run docker:build:prod
      - name: Push Docker images to ECR
        run: |
          npm run docker:push-to-ecr
      - name: Upload tag artifact for later reuse
        uses: actions/upload-artifact@v1
        with:
          name: tag
          path: tag.txt
